import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import ThemeToggle from "./components/ThemeToggle"; // Import the ThemeToggle component
import { ThemeProvider } from "next-themes"; // Import ThemeProvider to manage dark/light theme

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap everything in the ThemeProvider for theme management */}
        <ThemeProvider attribute="class" defaultTheme="light">
          <Navbar />
          <ThemeToggle /> {/* You can place ThemeToggle inside Navbar or elsewhere */}
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
